apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-cfg
data:
  DJANGO_DEBUG: {{ .Values.env.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.env.DJANGO_ALLOWED_HOSTS | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}
  JWT_ACCESS_TTL: {{ .Values.env.JWT_ACCESS_TTL | quote }}
  JWT_REFRESH_TTL: {{ .Values.env.JWT_REFRESH_TTL | quote }}
