{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.DJANGO_SECRET_KEY | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
  TG_BOT_TOKEN: {{ .Values.secrets.TG_BOT_TOKEN | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.JWT_PRIVATE_KEY | quote }}
  JWT_PUBLIC_KEY: {{ .Values.secrets.JWT_PUBLIC_KEY | quote }}
{{- end }}
