{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot.fullname" . }}-secret
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
  DB_DSN: {{ .Values.secrets.dbDsn | quote }}
{{- end }}
