apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-bot.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "telegram-bot.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
