apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "api-gateway.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-gateway.fullname" . }}
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "api-gateway.fullname" . }}-cfg
          {{- if .Values.secrets.create }}
            - secretRef:
                name: {{ include "api-gateway.fullname" . }}-secret
          {{- end }}
