{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
type: Opaque
stringData:
  JWT_PUBLIC_KEY: {{ .Values.secrets.JWT_PUBLIC_KEY | quote }}
{{- end }}
