apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "message-service.fullname" . }}-cfg
data:
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  SOCKETIO_PATH: {{ .Values.env.SOCKETIO_PATH | quote }}
  SOCKETIO_NAMESPACE: {{ .Values.env.SOCKETIO_NAMESPACE | quote }}
  CORS_ORIGINS: {{ .Values.env.CORS_ORIGINS | quote }}
