{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "message-service.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "message-service.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "message-service.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-redis
spec:
  type: ClusterIP
  selector:
    app: {{ include "message-service.fullname" . }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}
